### ISSUE TITLE
Is implemented effect_range as numbers?

### ISSUE THREAD

**Issue by sanslash332** [soundmud/soundrts#102]
Viewing the code, on the last comits, for effect_range properties is forced to changed (in code) square and nearby to numbers (6 and 12 respectively)
Is this change implemented on 1.2a10r1?

I ask for use numeric values instead of words in a mod code.

**Comment by soundmud** [comment]
I don't think so. Check the modding documentation released with the game to be sure.
On the other hand, maybe alpha 10 is not a version you should rely on. Wait for the next version until the end of the month or so.
