### ISSUE TITLE
add effect_range to object of effect class.

### ISSUE THREAD

**Issue by sanslash332** [soundmud/soundrts#103]
Add this parameter to the effect class, to indicate the range of, for example a harm effect.
In the ability class, with effect_range you set the range that allows to you cast the ability itself, but not the range of the effect.
For example, if you want cast a explosion you can set effect_range 6 to indicate that the summoner must be in the square that you want be the center of the effect, but you can't say that you want your explosion have a range of 24 with a harm_level x to affect all objects on that range.
A trick that you can do (for now) is the effect turn in to summon x, where x is a unit that have a massive attack with that range and splash damage (and a dekai after the explosion), but you with that can't set a specific target for that damage, like with harm effect.
Add this same behavior to effects like heal or something similar.

**Comment by soundmud** [comment]
I think it's already done.
To check the current version clone the repository with Git or download a zip from this URL:
https://github.com/soundmud/soundrts/zipball/master
