### ISSUE TITLE
Loading Boats Does not Work

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#114]
I have been testing version 1.2-c12 and I think that loading units into boats does not work.
I have mainly tested the map JL7. It seems to be simply due to the fact that ground units can't move to water squares (only build on them in certain cases). I don't know how to fix this, but my suggestion is to allow ground units to go to squares where shipyards can be built. In these cases using the CTRL key in conjunction wit the arrow keys should not be needed in order to navigate the map. Once on such a square, builder units should be allowed to build buildings that have to be placed on water type squares (such as a shipyard).
Additionally, ground units could perhaps be restricted to only be able to go to and build things on water squares that have a path leading to them. In other words, no ground units would be able to go to or build on a water square, if there wasn't a path leading to it. These are just my suggestions - feel free to do as you see fit.

**Comment by sanslash332** [comment]
hem @MatejGolian how do you are performing the load of units in to boats?

For me works fine, without problem.

* Put the units in a square near to the water square
* put the boat on that water square
* the ground and the water must be at the same height, so plateaus don't work.
* select the "load all from" skill of the boat
* press enter on the ground square where your units are waiting
* voila, the units board the boat.

if you are talking about the classic behavior of select the transport as a target for the default move option of a unit, for me seems legit that doesn't work in the case of boats of something similar; specially if they are on diferent squares.

probably work if the boat and the soldiers are on a water_ground_square, like big bridges.

for your maps, probably  you can create coast squares, that are water_ground and represents the border of a river, sea, etc.

**Comment by MatejGolian** [comment]
Thank you, I'll test your suggestions - it's possible that I have been doing something wrong.
I'll report back with my results.
Thanks and have fun.

**Comment by MatejGolian** [comment]
You were right. It works - I was doing it the wrong way. :-)
