### ISSUE TITLE
Loading maps in server crashes on Fedora 32

### ISSUE THREAD

**Issue by Finnboy94** [soundmud/soundrts#126]
I put up a server on Fedora 32 and everything went fine until I tried to select a map in the maps menu. Attached is the server.log file.
[server.log](https://github.com/soundmud/soundrts/files/5010318/server.log)

**Comment by Finnboy94** [comment]
Apparently this only happens with some maps, like Can1.txt. Z5 I could play when I tested.

**Comment by soundmud** [comment]
Thanks for the report. I have fixed this bug yesterday and will make a release soon. In the meantime if you really want to play a map, remove the comments (lines starting with a semicolon) with special characters.
