### ISSUE TITLE
Bug: Map Editor deletes global_food_limit

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#131]
Hello,
Currently, after editing a map with the built-in map editor, the re-saved map file no longer contains the global_food_limit command. It would be nice if this could get fixed. Otherwise the map editor works pretty reliably.
Many thanks.

**Comment by soundmud** [comment]
Fixed. Thank you!

**Comment by MatejGolian** [comment]
Don't mention it... :-)
