### ISSUE TITLE
Bug: Mage Recalls Water Units to Non-water Squares

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#132]
If you use a mage to recall units that reside on a water-type square such as sea or ocean, the recalled units get placed exactly where the mage is. The way the recall ability currently works is fine for ground- and air-type units, but I think that it poses a problem when it comes to water-type ones, because these units get inadvertently stuck on the square where the mage is and there's absolutely no way of moving them back to a water square. So, I think that water units should get recalled to an adjacent water square relative to where the mage is. In case multiple such squares exist, maybe the water units could land on a random (but still adjacent) one. And if there's no such square adjacent to the mage, perhaps recalling these units should fail. And to keep things more simple and predictable, in case there are both air and water-type  units among those that are to be recalled, maybe everything should end up placed where the water units do. What do you think?

**Comment by soundmud** [comment]
Maybe the game should recall only the units compatible with the destination?
A flying mage or a floating mage in a water square would be able to recall boats.

**Comment by soundmud** [comment]
The default mage wouldn't be able to recall boats.

**Comment by MatejGolian** [comment]
@soundmud , sounds reasonable. Honestly, you come up with really fun and creative solutions.

**Comment by paxcoder** [comment]
good ideas.
