### ISSUE TITLE
Can't Change Server Name in Debian 11

### ISSUE THREAD

**Issue by slannon97** [soundmud/soundrts#138]
I'm running the server from source on Debian 11. It works, but it shows up in the server list as player. I tried modifying config.py to change it from player to slannon, but this doesn't work. How do I change the server name in the list?

**Comment by soundmud** [comment]
config.py contains the default values.
The config file is in user/SoundRTS.ini

**Comment by slannon97** [comment]
Creating the user folder in the main folder for the game fixed the issue. I was able to find and change the name in SoundRTS.ini. Thank you.
