### ISSUE TITLE
cx_freeze makes valid macOS build

### ISSUE THREAD

**Issue by paxcoder** [soundmud/soundrts#145]
Hi.
I want you all to know that I can build sound RTS without problems on my m1 mac with cx_freeze!
why there are no mac builds ready to download?

**Comment by soundmud** [comment]
Hi. Thank you for the info and the pull request! I will check it soon.

**Comment by paxcoder** [comment]
done, will add some fixes soon ish to make it work better

**Comment by paxcoder** [comment]
forgot to close
