### ISSUE TITLE
fix or remove walls and gates

### ISSUE THREAD

**Issue by soundmud** [soundmud/soundrts#69]
The experimental "walls and gates" feature have several issues.

- Destroyed walls (I think) sometimes cause a concerning bug with the Player.observed_squares dictionary. Walls are tricky because they belong to 2 squares at the same time.
- Peasants building a gate sometimes move to the other side of the gate.
- It is not possible to open a gate (to attempt an exit) if the enemy is nearby. Maybe a gate could be morphed to an "open gate" using the upgrade_to action (like the flying townhall).
- The AI doesn't know how to build walls and gates yet. The AI would eventually have to know how to open and close a gate too.

A solution could be to solve at least the very annoying bug, then release and get feedback about this feature and eventually remove it. Many RTS don't have walls "nowadays", but this is not an excuse. The sound of a portcullis closing or opening would be great.

**Comment by sanslash332** [comment]
The idea of fix the walls using a morfing solution sounds very well :P

 

If you can finally implement it, it will be a good new feature to the game :P

**Comment by soundmud** [comment]
I have found where the bug came from. Walls and gates mask the next square from the enemy, and when a wall is destroyed or a gate is opened or closed, an update of the perception is required, which is missing. Unfortunately, to improve performance, the visibility code is already a bit complex, and I'm reluctant to add more complexity. For now, I will make walls and gates "transparent", and I'll improve that later if this feature is really appreciated.

About gates, for now, the simplified solution might be to just always allow friendly units to go through the gate, even if an enemy is there.

**Comment by soundmud** [comment]
This feature is probably good enough for now.
