### ISSUE TITLE
problems with upgradeable walls and gates

### ISSUE THREAD

**Issue by blackmagicgirl** [soundmud/soundrts#70]
If you make a gate or wall upgradeable, or in fact give it any ability that makes it show up in the building list, it's name is not spoken as you cycle through the list with w. Just it's location.

More problematically, if you upgrade it, to a newer type of gate or wall, the resulting upgrade building is no longer on the path and hence no longer blocking.

**Comment by soundmud** [comment]
Thanks for the report! I'll fix this soon.

**Comment by soundmud** [comment]
Fixed in 9bdef6b1bd5437b8bdd89010d9ecf7afb04d5381 and 7fd857c2bd7ad651751c4c4f849cfc50bbf3d346 .
