### ISSUE TITLE
Wrong Message when Exit Blocked

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#71]
If you send an unit to block a path or bridge and you reselect it after it successfully blocks what it's supposed to, the message that is spoken is wrong. For example, instead of "you control 1 peasant block path" it says "you control 1 peasant block peasant".
This might be true for other similar situations as well.

**Comment by soundmud** [comment]
It's not too bad, but since this new feature seems to be there to stay, I'll try to polish the interface.

**Comment by soundmud** [comment]
Fixed by 7fd857c2bd7ad651751c4c4f849cfc50bbf3d346 .
