### ISSUE TITLE
The Items 'Mods' and 'Soundpacks' in the options menu Are Not Translatable

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#72]
The title says it all really.

**Comment by soundmud** [comment]
Yes, if those sub menus are good enough, it might be time to add a proper label to their items in the main menu.

**Comment by thgcode** [comment]
According to this commit
https://github.com/soundmud/soundrts/commit/68212b089c760e5c733db0af96f685cf04ec87b9
the issue was resolved.

**Comment by MatejGolian** [comment]
Thanks, time to close then. :-)
