### ISSUE TITLE
Enable Moving on the Map with the Arrow Keys from and to Squares that Have Allied Gates Built on Them

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#74]
Right now if  you build a gate on a particular square you have to use ctrl + one of the arrow keys to move to the next square. For example, if you build a gate on a path to the north, you have to use ctrl + up to move to the square above. I think it would be a good idea to allso allow the commands without ctrl to pass in case of allied gates and maybe even all other allied objects that block an exit, but let friendly units pass.
I don't know if this is difficult to implement, but I think it would make sense since it would reflect how friendly units can move on the map.

**Comment by soundmud** [comment]
Thanks for the report! This one is fixed by 70cbad3c90f3858432510f8df7818cdd21ae603f . Sorry for not releasing the fix as a compatible revision of alpha 10. I hope alpha 11 will come soon enough.

**Comment by MatejGolian** [comment]
Me too, SoundRTS is the best game there is and I hope we'll see many
more new releases of it.<div
id="DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #aaabb6;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/2016/icons/icon-envelope-tick-round-orange-v1.png"
/></a></td>
		<td style="width: 470px; padding-top: 20px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Bez virů. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2016-05-22 19:24 GMT+02:00, soundmud <notifications@github.com>:
