### ISSUE TITLE
Feature Request: Peasants Would Need Dwelling Houses

### ISSUE THREAD

**Issue by MatejGolian** [soundmud/soundrts#81]
This might not be a missed feature, but I said to myself that I'll post it here anyway as apart from this I don't have any more ideas for the game.
fighting units live in barracks, but where do peasants live? The townhall doesn't make a lot of sense.
As I say, this is a marginal issue, but maybe it's worth considering.
No more requests from me - at least for now. :D

**Comment by blackmagicgirl** [comment]
Ah but do the soldiers actually live in the barracks? Or is that just where they go to be trained?
I've always sort of seen it as, this is my little country, and my soldiers are my people who go train to fight. My workers are the people who train to be my little slaves that say "Yes master?
So perhaps you have an entire civilization of people, and those who want to fight go to your barracks for training, and those who want to obey your every command go to your townhall to train in the arts of serving their "benevolent!" overlord...
I assumed all the non-workers and non-soldiers in my land just lived on the farms, and therefore are irrelevant to my benevolent dictatorship. :P

**Comment by MatejGolian** [comment]
I haven't looked at it that way. :D
Now when I think about it it makes complete sense that all the people would actually live on the farms. After all the number of farms you have directly determines how many people you can produce and this in deed suggests that every single unit has a farm to live on. Even such units like dragons. :D
I suggested dwelling houses because I know older versions of Age of Empires had them for example (don't know about the newer ones), but than again I'm not sure if Age of Empires had farms or not.

**Comment by blackmagicgirl** [comment]
Well more importantly, you, as your people's benevolent dictator, shouldn't concern yourself with such things as how the common worker lives! That they say, "Yes master?" when you say bring me gold should be enough!

**Comment by MatejGolian** [comment]
Well, what can I say? I like games with a lot of realistic elements. :D

**Comment by sanslash332** [comment]
Hmm This isn’t a really issue or feature request for the core.

 

Remember, that the soundrts isn’t a complete game, is a game core, that you can configure an mod as you want.

 

For example, if you want put houses plus the farm, you can add it in your mod through rules txt.

 

And, well, the farms provides to you food, but the houces manage the poblation number.

 

Analicing that, we encounter a real feature request to the core.

 

The feature is can create more resources like food, and the buildings can provide that.

With it, you can use food, and poblation, or if you have a magic race, you need magic plus food for control your mages, etc etc etc.

**Comment by MatejGolian** [comment]
I understand what you're saying. I do think however that it's up to @SoundMud to decide if a particular thing should belong to the game core or not. That being said I have already closed this issue as I no longer deem it relevant.
